### ISSUE TITLE
ReCAPTCHA couldn't find user-provided function: vueRecaptchaApiLoaded

### ISSUE THREAD

**Issue by shrikant190890** [drozdzynski/vue-grecaptcha#8]
Unknown custom element: <vue-grecaptcha> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

**Comment by drozdzynski** [comment]
If you use build tool you must do:
```js
require('vue-grecaptcha')

Vue.use(VueGrecaptcha, {
  // options
})
```
Then it will global and will work.
This will not work: `import VueGrecaptcha from 'vue-grecaptcha'`, I know this issue and will fix it later.
